CREATE DATABASE DATA_AY;
USE DATA_AY;
SELECT * FROM DATA_ANALYTICS_DATASET;

-- BASIC LEVEL

-- 1 FIND ALL EMPLOYEES WITH SALARY>70000
SELECT  EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,DEPARTMENT FROM DATA_ANALYTICS_DATASET
WHERE SALARY>70000;

-- 2 LIST EMPLOYEES SORTED BY EXPERIENCE(HIGHEST)
SELECT EMPLOYEE_ID,EMPLOYEE_NAME,JOB_ROLE,EXPERIENCE_YEARS FROM DATA_ANALYTICS_DATASET
ORDER BY EXPERIENCE_YEARS DESC;

-- 3 COUNT EMPLOYEES IN EAC DEPARTEMENT
SELECT DEPARTMENT,COUNT(*) FROM DATA_ANALYTICS_DATASET
GROUP BY DEPARTMENT;

-- INTERMEDIATE LEVEL

-- 4 FIND THE AVG SALARY PER DEPARTMENT
SELECT DEPARTMENT,AVG(SALARY) FROM DATA_ANALYTICS_DATASET
GROUP BY DEPARTMENT;

-- 5 FIND EMPLOYEES WHOSE PERFORMANCE RATING IS ABOVE THE OVERALL AVERAGE
SELECT EMPLOYEE_NAME,PERFORMANCE_RATING FROM DATA_ANALYTICS_DATASET
WHERE PERFORMANCE_RATING>(SELECT AVG(PERFORMANCE_RATING) FROM DATA_ANALYTICS_DATASET);

--  6 FIND THE TOP 3 HIGHEST PAID EMPLOYEES
SELECT EMPLOYEE_NAME,SALARY,JOB_ROLE FROM DATA_ANALYTICS_DATASET
ORDER BY SALARY DESC
LIMIT 3;

-- 7 FIND DEPARTMENTS WHOSE AVERAGE  SALARY EXCEEDS 70000
SELECT DEPARTMENT,AVG(SALARY) FROM DATA_ANALYTICS_DATASET
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>70000;

-- ADVANCED LEVEL
-- 8 RANK EMPLOYEE BY SALARY WITHIN EACH DEPARTEMENT
SELECT EMPLOYEE_NAME,DEPARTMENT,SALARY,
RANK() OVER(PARTITION BY DEPARTMENT  ORDER BY SALARY DESC) 
FROM DATA_ANALYTICS_DATASET;

-- 9 FIND THE  EMPLOYEE WITH MAX PROJECT COMPLETE IN EACH DEPARTMENT
SELECT  DEPARTMENT,EMPLOYEE_NAME,PROJECTS_COMPLETED
FROM DATA_ANALYTICS_DATASET D1
WHERE PROJECTS_COMPLETED=(SELECT MAX(PROJECTS_COMPLETED) FROM DATA_ANALYTICS_DATASET D2
WHERE D1.DEPARTMENT=D2.DEPARTMENT);

-- 10 FIND EMPLOYEE WHO EARN MORE THAN THEIR DEPARTMENT'S AVERAGE
SELECT EMPLOYEE_NAME,DEPARTMENT,SALARY 
FROM DATA_ANALYTICS_DATASET D1
WHERE SALARY>(SELECT AVG(SALARY) FROM DATA_ANALYTICS_DATASET D2
WHERE D1.DEPARTMENT=D2.DEPARTMENT);

-- SCENARIO BASED QUESTION
-- 11 FIND HIGHEST PERFORMER WITH LOWEST RATING
SELECT EMPLOYEE_NAME,SALARY,PERFORMANCE_RATING FROM DATA_ANALYTICS_DATASET
WHERE PERFORMANCE_RATING=(SELECT MAX(PERFORMANCE_RATING) FROM DATA_ANALYTICS_DATASET)
ORDER BY SALARY ASC
LIMIT 1;

-- 12 RUNNING TOTAL OF SALARY  ORDERED BY JOINING DATE
SELECT EMPLOYEE_NAME,JOINING_DATE SALARY,
SUM(SALARY) OVER(PARTITION  BY JOINING_DATE) AS  RUNNING_TOTAL
FROM DATA_ANALYTICS_DATASET;

-- 13 CATEGORIZE EMPLOYEE BY EXPERIENCE LEVEL
SELECT EMPLOYEE_NAME,EXPERIENCE_YEARS,
CASE
WHEN EXPERIENCE_YEARS<2 THEN 'JUNIOR'
WHEN EXPERIENCE_YEARS BETWEEN 2 AND 5 THEN 'MID-LEVEL'
ELSE 'SENIOR'
END AS EXPERIENCE_LEVEL
FROM DATA_ANALYTICS_DATASET;
