CREATE DATABASE NETFLIX;
USE NETFLIX;
SELECT * FROM NETFLIX_SHOWS;

--  BASIC LEVEL
-- 1 RETRIEVE ALL THE DATA FROM THE TABLE
SELECT * FROM  NETFLIX_SHOWS;

-- 2 HOW MANY TOTAL/SHOW OR MOVIE IN NETFLIX
SELECT COUNT(*) FROM NETFLIX_SHOWS;

-- 3 LIST ALL DISTINCT CONTENT TYPES AVAILABLE IN THE DATASET
SELECT DISTINCT TYPE
FROM NETFLIX_SHOWS;

-- 4 FETCH ALL MOVIES FROM DATA SET
SELECT * FROM NETFLIX_SHOWS
WHERE TYPE='MOVIE';

-- 5 GET ALL TITLES RELEASE IN THE YEAR 2021
SELECT TITLE,TYPE,RELEASE_YEAR FROM NETFLIX_SHOWS
WHERE RELEASE_YEAR=2021;

-- INTERMEDIATE  LEVEL 
-- 6 LIST ALL CONTENET WITH TV-MA RATING
SELECT TITLE,TYPE,RATING,RELEASE_YEAR
FROM NETFLIX_SHOWS
WHERE RATING='TV-MA';

-- 7 FIND ALL SHOWS WHERE DIRECTOR IS MISSING NULL
SELECT TITLE,TYPE,COUNTRY
FROM NETFLIX_SHOWS
WHERE DIRECTOR IS NULL;

-- ADVANCED LEVEL
-- 8  DETECT DUPLICATE TITLE IN THE DATASET
SELECT COUNT(*),TITLE FROM NETFLIX_SHOWS
GROUP BY TITLE
HAVING COUNT(*)>1;

-- 9 WRITE A QUERY TO CLASSIFY CONTENT AS OLD (<2015),'RECENT'(2015-2019) OR 'NEW'(2020+)
SELECT TITLE,RELEASE_YEAR,
CASE
WHEN RELEASE_YEAR <2015 THEN 'OLD'
WHEN RELEASE_YEAR BETWEEN 2015 AND 2019 THEN 'RECENT'
ELSE 'NEW'
END AS CONTENT_ERA
FROM NETFLIX_SHOWS
ORDER BY RELEASE_YEAR;




