CREATE DATABASE COMPLAINTS;
USE COMPLAINTS;
SELECT  * FROM LONG_GENDER_VIOLENCE_DATASET;

-- 1  FIND TOTAL COMPLAINTS IN ALL REGION 
SELECT REGION,SUM(COMPLAINTS) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP  BY REGION;

-- 2 FIND AVG UNEMPLOYEMENT RATE 
SELECT AVG(UNEMPLOYMENT_RATE_PERCENTAGE) FROM LONG_GENDER_VIOLENCE_DATASET;

-- 3 SHOW DISTINCT REGION
SELECT DISTINCT REGION FROM LONG_GENDER_VIOLENCE_DATASET;

-- 4 FIND TOP 5 REGION   WITH HIGHEST COMPLAINTS
SELECT REGION,MAX(COMPLAINTS) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY REGION
LIMIT 5;

-- 5 FIND REGION WITH  HIGHEST VIOLENCE VICTIM
SELECT REGION,MAX(VIOLENCE_VICTIMS) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY REGION ;

-- 6 FIND AVG SCHOOL LEAVING PERCENTAGE  BY REGION
SELECT REGION,AVG(SCHOOL_LEAVING_PERCENTAGE) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY REGION;

-- 7 Find regions where unemployment rate is greater than 10%
SELECT REGION,UNEMPLOYMENT_RATE_PERCENTAGE FROM LONG_GENDER_VIOLENCE_DATASET
WHERE UNEMPLOYMENT_RATE_PERCENTAGE>10;

-- 8 Find year-wise total complaints
SELECT YEAR,SUM(COMPLAINTS) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY YEAR
ORDER BY YEAR;

-- 9  Find funding provided to each region
SELECT REGION,SUM(FUNDING_EUR) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY REGION;

-- 10 Find top 3 regions with highest funding
SELECT REGION,MAX(FUNDING_EUR) FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY REGION
LIMIT 3;

-- 11 Find complaint-to-victim ratio
SELECT REGION,COMPLAINTS,VIOLENCE_VICTIMS,
(COMPLAINTS/VIOLENCE_VICTIMS)*100
FROM LONG_GENDER_VIOLENCE_DATASET;

-- 12  Find regions having complaints greater than average complaints
SELECT REGION,COMPLAINTS  FROM LONG_GENDER_VIOLENCE_DATASET
WHERE COMPLAINTS>(SELECT AVG(COMPLAINTS) FROM LONG_GENDER_VIOLENCE_DATASET);

-- 13 Rank regions by complaints using window function
SELECT REGION,SUM(COMPLAINTS) ,
RANK() OVER(ORDER BY SUM(COMPLAINTS) DESC) 
FROM LONG_GENDER_VIOLENCE_DATASET
GROUP BY REGION;

-- 14 Find cumulative complaints year-wise
SELECT YEAR,SUM(COMPLAINTS) AS TOTAL_COMPLAINTS,
SUM(SUM(COMPLAINTS)) OVER(ORDER BY YEAR)
FROM LONG_GENDER_VIOLENCE_DATASET
GROUP  BY YEAR;








